### ISSUE TITLE
qt-creator-4.9: use clang needs >=clang 7.0

### ISSUE THREAD

**Issue by klimentyev** [dev-0x7C6/dev1990-overlay#1]
I tried build this version with clang use, but I had error at compiling. I see that clang and llvm would be updated to 7.0 and greater.
https://code.qt.io/cgit/qt-creator/qt-creator.git/tree/README.md

**Comment by klimentyev** [comment]
@dev-0x7C6 What version of the clang do you use? I've an error for stable clang-6.0.1 and use clang.

**Comment by dev-0x7C6** [comment]
Currently I'm using:

[ebuild   R   ~] sys-devel/clang-8.0.0:8::gentoo
[ebuild   R   ~] sys-devel/llvm-8.0.0:8::gentoo

I have ~amd64 keywords for llvm and clang (and other toolchain parts) for sometime

**Comment by klimentyev** [comment]
> I have ~amd64 keywords for llvm and clang (and other toolchain parts) for sometime

OK, thx. So, I will update my llvm/clang package.

**Comment by dev-0x7C6** [comment]
Fixed in https://github.com/dev-0x7C6/dev1990-overlay/commit/dcd8ab0874da9768e402c120d250b84552be8431

**Comment by klimentyev** [comment]
@dev-0x7C6 Thank you.
