### ISSUE TITLE
dev-qt/qt-creator-4.11.0_beta2 fails to build

### ISSUE THREAD

**Issue by klimentyev** [dev-0x7C6/dev1990-overlay#3]
I can't build Qt Creator due to error at compile.
[build.log](https://github.com/dev-0x7C6/dev1990-overlay/files/3826269/build.log)

**Comment by dev-0x7C6** [comment]
dev-qt/qt-creator-4.11.0_beta2 is now masked. I tested qt-creator-9999 (Qt Creator 4.11.0-rc1 (4.10.84) from git) and compilation was successful, so the idea is to wait for offical 4.11.0-rc1 release.

In future I'll avoid adding ~amd64 keywords on beta and rc builds.

**Comment by dev-0x7C6** [comment]
But still the latest version have broken clang-format integration, this is correlated to #2. Upstream patches against LLVM/Clang was rejected. No idea how this is going to play out.

**Comment by klimentyev** [comment]
Thanks! I will wait stable work version.
