### ISSUE TITLE
dev-qt/qt-creator-4.12.2::dev1990-overlay failed

### ISSUE THREAD

**Issue by d351d3r** [dev-0x7C6/dev1990-overlay#5]
I don't use KDE, and emake failed. 
```
cat /etc/portage/package.use/qt-creator
dev-qt/qt-creator autotest clang designer git help qmldesigner webengine cmake cppcheck ctfvisualizer cvs doc glsl mercurial qbs qmlprofiler subversion
```

[build.log](https://github.com/dev-0x7C6/dev1990-overlay/files/4775799/build.log)

**Comment by d351d3r** [comment]
On the old system, where the window Manager was KDE, everything was collected. It seems to me that some dependencies are missing. Eg:
```
qdoc: warning: "Qt Creator" Cannot locate index file for dependency "qtwidgets"
qdoc: warning: "Qt Creator" Cannot locate index file for dependency "qtcore"
..
```
```
/var/tmp/portage/dev-qt/qt-creator-4.12.2/work/qt-creator-opensource-src-4.12.2/src/plugins/coreplugin/locator/locatorfiltertest.h:30:10: error: 'QTest' file not found
/var/tmp/portage/dev-qt/qt-creator-4.12.2/work/qt-creator-opensource-src-4.12.2/src/plugins/coreplugin/locator/locatorfiltertest.h:84:25: error: no function template matches function template specialization 'toString'
```

**Comment by dev-0x7C6** [comment]
I wasn't able to reproduce this issue. I tried to remove `dev-qt/qttest` (installed by some packages from KDE) manually and check if this is triggering  `'QTest' file not found`, but that wasn't a case.

Can you reproduce this issue with `dev-qt/qttest` installed manually ?

I'll upload updated ebuild with contains recent changes, but I'm unsure if this helps.

**Comment by d351d3r** [comment]
> I wasn't able to reproduce this issue. I tried to remove `dev-qt/qttest` (installed by some packages from KDE) manually and check if this is triggering `'QTest' file not found`, but that wasn't a case.
> 
> Can you reproduce this issue with `dev-qt/qttest` installed manually ?
> 
> I'll upload updated ebuild with contains recent changes, but I'm unsure if this helps.

I already had qttest installed
```
eix qttest
[I] dev-qt/qttest
Available version:
(4) 4.8.2020.02[1]
( (5) 5.14.2(5/5.14)^t (~)5.15.0(5/5.15)^t
{ {aqua debug +exceptions pchtest AFI_MISS="n 32 n 64o32" ABI_PRISM="lp64 lp64d" ABE_S 390="32 64" ABI_X86="32 64 x32"}
Installed versions: 5.15.0 (5/5.15)^t (06:12:40 04.06.2020)(-debug -test)
Home page: https://www.qt.io/
Description: Unit testing library for the Qt5 framework
```

**Comment by d351d3r** [comment]
The update to the latest version of dev-qt/qt-creator-4.12.2-r1 was successful.
