### ISSUE TITLE
media-gfx/prusa-slicer-2.3.0_rc3 fails to link to GTK3

### ISSUE THREAD

**Issue by hvraven** [dev-0x7C6/dev1990-overlay#7]
Hi. Thanks for taking care of prusa-slicer in your repo :-)

The latest rc fails to build because it does not link properly to gtk3. Its a known upstream bug, see the issue here: https://github.com/prusa3d/PrusaSlicer/issues/5722 On the bottom a PR is linked with a simple patch to fix the issue: https://github.com/prusa3d/PrusaSlicer/pull/5717 . Downloading the patch into files and adding it to `PATCHES` fixes the issue.

Will most likely be fixed in the next version as well, but the rc2 has a crash bug which is fixed in rc3, so I looked for a solution. Though I share my findings.

**Comment by dev-0x7C6** [comment]
Thanks for pinpointing. Fixed with d4228a808231a07b1652c59e31c2a4f199835c3c.
