### ISSUE TITLE
GitLab runner update

### ISSUE THREAD

**Issue by SWSAmor** [dev-0x7C6/dev1990-overlay#8]
Please if you have spare time update gitlab-runner. There is version 13.x but 12.x in overlay. Thx.

**Comment by dev-0x7C6** [comment]
I updated to 13.11.0, right now I don't have environment to test it, please send me feedback.

**Comment by SWSAmor** [comment]
OMG you are so fast. Thank you. I will try and back.

**Comment by SWSAmor** [comment]
Works perfectly. Thank you.
